Split Player into its own class
tyoungNIO/worstgame pull request #5
Opened 2017-10-03 17:06 UTC by hansmosh

2017-10-03 17:06 UTC, hansmosh commented
See #4 for comments

2017-10-03 22:30 UTC, shadetree01010100 requested changes
Please update the readme, otherwise this looks great.

2017-10-03 22:37 UTC, hansmosh commented
@tyoungNIO Updated the README

2017-10-04 01:57 UTC, shadetree01010100 approved these changes

2017-10-04 01:57 UTC, merged